/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.nkquest;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import net.mcreator.nkquest.gui.GuiWorldSetup;
import net.mcreator.nkquest.gui.GuiWorldOptions;
import net.mcreator.nkquest.gui.GuiTunerGUI;
import net.mcreator.nkquest.gui.GuiMindsetGUI;
import net.mcreator.nkquest.gui.GuiMindbendMenu;
import net.mcreator.nkquest.gui.GuiIronJukeboxGUI;
import net.mcreator.nkquest.gui.GuiGuidebookPage1;
import net.mcreator.nkquest.gui.GuiGoldenJukeboxGUI;
import net.mcreator.nkquest.gui.GuiEtcherGUI;
import net.mcreator.nkquest.gui.GuiDiamondJukeboxGUI;
import net.mcreator.nkquest.gui.GuiDashShellGUI;
import net.mcreator.nkquest.gui.GuiClassSelect;
import net.mcreator.nkquest.gui.GuiCharacterSelect;
import net.mcreator.nkquest.gui.GuiCharResetWarning;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsNkquest implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsNkquest() {
		sounds.put(new ResourceLocation("nkquest", "nkquest.entity.dimtp"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.entity.dimtp")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.entity.invisible"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.entity.invisible")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.entity.visible"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.entity.visible")));
		sounds.put(new ResourceLocation("nkquest", "nkquest_race.record.raceintro"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest_race.record.raceintro")));
		sounds.put(new ResourceLocation("nkquest", "nkquest_race.record.nitrocircuit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest_race.record.nitrocircuit")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.auroraaltitude.1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.auroraaltitude.1")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.auroraaltitude"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.auroraaltitude")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.greatgorge1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.greatgorge1")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.greatgorge2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.greatgorge2")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.greatgorge3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.greatgorge3")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.auroraaltitude.3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.auroraaltitude.3")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.cargocanyon1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.cargocanyon1")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.cargocanyon2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.cargocanyon2")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.cargocanyon3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.cargocanyon3")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.lightninglift1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.lightninglift1")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.lightninglift2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.lightninglift2")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.lightninglift3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.lightninglift3")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.hijinxheights1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.hijinxheights1")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.hijinxheights2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.hijinxheights2")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.record.nk.hijinxheights3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.record.nk.hijinxheights3")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.entity.magicblastcharge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.entity.magicblastcharge")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.entity.magicblastfire"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.entity.magicblastfire")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.block.capsulebreak"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.block.capsulebreak")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.block.paradisestaractivate"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.block.paradisestaractivate")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.ambient.dash_boost"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.ambient.dash_boost")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.master.dash_boost2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.master.dash_boost2")));
		sounds.put(new ResourceLocation("nkquest", "nkquest.ambient.nkspring"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("nkquest", "nkquest.ambient.nkspring")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsNkquest.ModElement.class)
					elements.add((ElementsNkquest.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsNkquest.ModElement::initElements);
		this.addNetworkMessage(NkquestVariables.WorldSavedDataSyncMessageHandler.class, NkquestVariables.WorldSavedDataSyncMessage.class, Side.SERVER,
				Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = NkquestVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = NkquestVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				Nkquest.PACKET_HANDLER.sendTo(new NkquestVariables.WorldSavedDataSyncMessage(0, mapdata), (EntityPlayerMP) event.player);
			if (worlddata != null)
				Nkquest.PACKET_HANDLER.sendTo(new NkquestVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = NkquestVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				Nkquest.PACKET_HANDLER.sendTo(new NkquestVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			Nkquest.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiDashShellGUI.GUIID)
				return new GuiDashShellGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMindbendMenu.GUIID)
				return new GuiMindbendMenu.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMindsetGUI.GUIID)
				return new GuiMindsetGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiCharacterSelect.GUIID)
				return new GuiCharacterSelect.GuiContainerMod(world, x, y, z, player);
			if (id == GuiCharResetWarning.GUIID)
				return new GuiCharResetWarning.GuiContainerMod(world, x, y, z, player);
			if (id == GuiWorldSetup.GUIID)
				return new GuiWorldSetup.GuiContainerMod(world, x, y, z, player);
			if (id == GuiWorldOptions.GUIID)
				return new GuiWorldOptions.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidebookPage1.GUIID)
				return new GuiGuidebookPage1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiClassSelect.GUIID)
				return new GuiClassSelect.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGoldenJukeboxGUI.GUIID)
				return new GuiGoldenJukeboxGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiIronJukeboxGUI.GUIID)
				return new GuiIronJukeboxGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDiamondJukeboxGUI.GUIID)
				return new GuiDiamondJukeboxGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTunerGUI.GUIID)
				return new GuiTunerGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiEtcherGUI.GUIID)
				return new GuiEtcherGUI.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiDashShellGUI.GUIID)
				return new GuiDashShellGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiMindbendMenu.GUIID)
				return new GuiMindbendMenu.GuiWindow(world, x, y, z, player);
			if (id == GuiMindsetGUI.GUIID)
				return new GuiMindsetGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiCharacterSelect.GUIID)
				return new GuiCharacterSelect.GuiWindow(world, x, y, z, player);
			if (id == GuiCharResetWarning.GUIID)
				return new GuiCharResetWarning.GuiWindow(world, x, y, z, player);
			if (id == GuiWorldSetup.GUIID)
				return new GuiWorldSetup.GuiWindow(world, x, y, z, player);
			if (id == GuiWorldOptions.GUIID)
				return new GuiWorldOptions.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidebookPage1.GUIID)
				return new GuiGuidebookPage1.GuiWindow(world, x, y, z, player);
			if (id == GuiClassSelect.GUIID)
				return new GuiClassSelect.GuiWindow(world, x, y, z, player);
			if (id == GuiGoldenJukeboxGUI.GUIID)
				return new GuiGoldenJukeboxGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiIronJukeboxGUI.GUIID)
				return new GuiIronJukeboxGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiDiamondJukeboxGUI.GUIID)
				return new GuiDiamondJukeboxGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiTunerGUI.GUIID)
				return new GuiTunerGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiEtcherGUI.GUIID)
				return new GuiEtcherGUI.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsNkquest elements;
		protected final int sortid;
		public ModElement(ElementsNkquest elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
